# Generated by Django 4.1.2 on 2022-11-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_join',
            new_name='date_joined',
        ),
    ]
